framework:
    rate_limiter:
        login:
            policy: 'fixed_window'
            limit: 5
            interval: '1 minute'
        registration:
            policy: 'fixed_window'
            limit: 3
            interval: '1 hour'
        token_refresh:
            policy: 'fixed_window'
            limit: 10
            interval: '1 minute'
        global_api:
            policy: 'sliding_window'
            limit: 100
            interval: '1 minute'