import "./globals.css";
import { ThemeModeScript } from "flowbite-react"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {



  return (
    <html suppressHydrationWarning lang='en'>
    <head>
      <ThemeModeScript />
    </head>
      <body
        className={`antialiased`}
      >
      {children}
      </body>
    </html>
  );
}
