# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    session.handler.redis:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        arguments:
            - '@Redis'  # This requires that we define a Redis client service
            - { prefix: 'session:', ttl: 86400 }  # Session config with 1 day TTL

    Redis:
        class: Redis
        calls:
            - [ connect, [ '%env(REDIS_HOST)%', '%env(int:REDIS_PORT)%' ] ]

    App\EventListener\JWTAuthenticationSuccessListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccess }
    # Register refresh token cleanup command
    App\Command\CleanupRefreshTokensCommand:
        arguments:
            $refreshTokenService: '@App\Service\RefreshTokenService'
        tags: [ 'console.command' ]

    app.cache.tag_aware:
        class: Symfony\Component\Cache\Adapter\TagAwareAdapter
        arguments:
            - '@cache.app'
    App\Service\CacheService:
        arguments:
            $cache: '@app.cache.tag_aware'
            $logger: '@logger'
            $cacheEnabled: '%kernel.debug%'



    # RateLimiter service
    App\Service\RateLimiterService:
        arguments:
            $loginLimiter: '@limiter.login'
            $registrationLimiter: '@limiter.registration'
            $tokenRefreshLimiter: '@limiter.token_refresh'
            $globalApiLimiter: '@limiter.global_api'

    App\EventListener\PreAuthenticationListener:
        tags:
            - { name: kernel.event_subscriber }

    App\EventListener\GlobalApiRateLimitListener:
        tags:
            - { name: kernel.event_subscriber }

    App\Service\RedisService:
        arguments:
            $redisConnectionString: '%env(REDIS_URL)%'