# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\EventListener\JWTAuthenticationSuccessListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccess }
    # Register refresh token cleanup command
    App\Command\CleanupRefreshTokensCommand:
        arguments:
            $refreshTokenService: '@App\Service\RefreshTokenService'
        tags: [ 'console.command' ]

    app.cache.tag_aware:
        class: Symfony\Component\Cache\Adapter\TagAwareAdapter
        arguments:
            - '@cache.app'
    App\Service\CacheService:
        arguments:
            $cache: '@app.cache.tag_aware'
            $logger: '@logger'
            $cacheEnabled: '%kernel.debug%'

    # Rate limiter factories
    app.rate_limiter.login:
        class: Symfony\Component\RateLimiter\RateLimiterFactory
        arguments:
            $config:
                policy: 'fixed_window'
                limit: 5
                interval: '1 minute'
            $storage: '@cache.rate_limiter'

    app.rate_limiter.registration:
        class: Symfony\Component\RateLimiter\RateLimiterFactory
        arguments:
            $config:
                policy: 'fixed_window'
                limit: 3
                interval: '1 hour'
            $storage: '@cache.rate_limiter'

    app.rate_limiter.token_refresh:
        class: Symfony\Component\RateLimiter\RateLimiterFactory
        arguments:
            $config:
                policy: 'fixed_window'
                limit: 10
                interval: '1 minute'
            $storage: '@cache.rate_limiter'

    app.rate_limiter.global_api:
        class: Symfony\Component\RateLimiter\RateLimiterFactory
        arguments:
            $config:
                policy: 'sliding_window'
                limit: 100
                interval: '1 minute'
            $storage: '@cache.rate_limiter'

    # RateLimiter service
    App\Service\RateLimiterService:
        arguments:
            $loginLimiter: '@app.rate_limiter.login'
            $registrationLimiter: '@app.rate_limiter.registration'
            $tokenRefreshLimiter: '@app.rate_limiter.token_refresh'
            $globalApiLimiter: '@app.rate_limiter.global_api'

    App\EventListener\PreAuthenticationListener:
        tags:
            - { name: kernel.event_subscriber }

    App\EventListener\GlobalApiRateLimitListener:
        tags:
            - { name: kernel.event_subscriber }